language: node_js
node_js:
  - 7

services: docker

before_install:
  - npm install -g eslint
  - npm run lint
  # TODO: npm run test

install:
  - ./docker_build.sh

deploy:
  provider: script
  script: bash ./deploy.sh