language: node_js
node_js:
  - 13

services: docker

script: 'true'

before_install:
  - npm ci
  - npm run lint
  # TODO: npm run test

install:
  - ./docker_build.sh

deploy:
  provider: script
  script: bash ./deploy.sh